# Generated by Django 3.2.3 on 2021-05-20 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tweet_field', models.CharField(max_length=280)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
